module.exports = {
  ACC: require("./acc.json"),
  AL1: require("./al1.json"),
  DB1: require("./db1.json"),
  DG1: require("./dg1.json"),
  DRG: require("./drg.json"),
  EVN: require("./evn.json"),
  GT1: require("./gt1.json"),
  IN1: require("./in1.json"),
  IN2: require("./in2.json"),
  IN3: require("./in3.json"),
  MSH: require("./msh.json"),
  NK1: require("./nk1.json"),
  OBX: require("./obx.json"),
  PD1: require("./pd1.json"),
  PID: require("./pid.json"),
  PR1: require("./pr1.json"),
  PV1: require("./pv1.json"),
  PV2: require("./pv2.json"),
  ROL: require("./rol.json"),
  UB1: require("./ub1.json"),
  UB2: require("./ub2.json"),
};
